default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: sample_3_development

test:
  <<: *default
  database: sample_3_test

production:
  <<: *default
  database: sample_3_production
  username: sample_3
  password: <%= ENV['SAMPLE_3_DATABASE_PASSWORD'] %>
